[book]
authors = ["msrocka"]
language = "en"
multilingual = false
src = "src"
title = "Inter-process communication with openLCA"

[build]
build-dir = "../docs/ipc"

[output.html]
mathjax-support = true
